### ISSUE TITLE
Product reviews are not showing on product pages

### ISSUE THREAD

**Issue by jackyl** [magefan/module-auto-related-product#2]
Using this plugin prevents any reviews to show on a product page, you can only see the number of reviews in the tab header.

See your demo, there are 2 reviews, but not showing at all:
https://arp.demo.magefan.top/rival-field-messenger.html

**Comment by magefan** [comment]
@jackyl , this issue has been fixed https://github.com/magefan/module-auto-related-product/commit/eb280b90ecc437472abd47825a8ed1397793cddb .

The new version 2.0.1 will be available the next week.
